name: Enhancement Request
description: Suggest a feature or improvement for the Chrome Extension.
title: "[Enhancement] <short description>"
labels: [enhancement]
assignees: []
 
body:
  - type: dropdown
    id: feature_area
    attributes:
      label: Relevant Feature Area
      description: Which area would you like to see improved?
      options:
        - Navigation Shortcuts
        - Dark Mode
        - Data Analyzer
        - Analytics Query
        - Other
    validations:
      required: true
 
  - type: textarea
    id: enhancement_summary
    attributes:
      label: Summary of Enhancement
      description: Describe your suggestion or improvement idea.
      placeholder: "Example: New shortcut link for ...."
    validations:
      required: true
 
  - type: textarea
    id: use_case
    attributes:
      label: Use Case / Benefit
      description: Why is this enhancement useful? Who will it benefit?
      placeholder: "Example: To speed up writing query..."
    validations:
      required: true
 
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Include screenshots, references, or similar feature examples (if any).
    validations:
      required: false
